language: go

go:
- master

os:
  - linux

dist: bionic

before_install:
  - sudo apt-get install -y ffmpeg mediainfo
addons:
  apt:
    update: true


after_success:
  - bash <(curl -s https://codecov.io/bash)