# Keep test at the top so that it is default when `make` is called.
# This is used by Travis CI.
test: build
	go test ./test/...
build:
	go build ./...
install: build
	go install ./...
inspect: build
	golint ./...